// app/way-forward/page.ts (or data/way-forward.ts if preferred as a data module)

// This file defines the data types and provides sample data for the
// "Way Forward: AI-Powered Recommendations" page.

// Note: This data structure focuses on recommendations and links to existing
// review/issue/opportunity data rather than duplicating it.

/**
 * Type for a single AI-generated recommendation.
 * This should guide UI display on the "Way Forward" page.
 */
export type Recommendation = {
    id: string; // Unique ID for the recommendation
    title: string; // A concise, actionable title for the recommendation
    issue_icon?: string; // The icon for the issue
    type: string; // The type of recommendation
    priority: 'high' | 'medium' | 'low'; // AI-assigned priority
    estimated_effort?: 'low' | 'medium' | 'high'; // Optional: Estimated effort to implement
    estimated_effort_days?: number; // Optional: Estimated effort in days
    expected_outcome: string; // What positive impact is expected
    ai_rationale: string; // Brief explanation from AI, linking to underlying analysis
    recommended_actions: recommended_actions[]; // The recommended actions to take
    
    // Links to source data (IDs that exist in other stores/data files)
    linked_analysis_ids: string[]; // Array of IDs of IssueAnalysis (from issuesData) this is based on
    
    // ID of a single representative review from your reviews store to display directly (e.g., in an accordion).
    // The actual review content will be fetched from the reviews store using this ID.
    representative_review_id?: string; // **FINAL UPDATE: Back to just the ID string**
    // The "More Reviews" link will be generated by filtering the main reviews page
    // based on the context of this recommendation (e.g., linked_analysis_ids).
};

export type RecSummary = {
    summary: string; // An AI-generated executive summary for the recommendations
    count: number; // The number of recommendations
    highPriorityCount: number; // The number of high priority recommendations
    mediumPriorityCount: number; // The number of medium priority recommendations
    lowPriorityCount: number; // The number of low priority recommendations
    highEffortCount: number; // The number of high effort recommendations
    mediumEffortCount: number; // The number of medium effort recommendations
    lowEffortCount: number; // The number of low effort recommendations
    highImpactCount: number; // The number of high impact recommendations
    mediumImpactCount: number; // The number of medium impact recommendations
    lowImpactCount: number; // The number of low impact recommendations
}
export type recommended_actions = {
    action_title: string;
    action_description: string;
    estimated_effort: 'low' | 'medium' | 'high';
    estimated_effort_days: number;
}

/**
 * Type for the overall "Way Forward" data, including a summary and the list of recommendations.
 */
export type AllRecommendationsData = {
    // summary: string; // An AI-generated executive summary for the recommendations
    recommendations: Recommendation[]; // The list of AI-powered recommendations
    recSummary: RecSummary; // The summary of the recommendations
};

/**
 * Sample data for AI-Powered Recommendations.
 * This data is designed to be consumed by the "Way Forward" page and its components.
 * It uses IDs to reference detailed data from other modules (e.g., issuesData, useReviewsStore).
 */
export const recommendationsData: AllRecommendationsData = {
    recSummary: {
        summary: "The AI identifies prioritizing user experience and transaction reliability as key areas for growth. Focusing on these opportunities is projected to significantly enhance overall app satisfaction and engagement in the coming quarter.",
        count: 6,
        highPriorityCount: 4,
        mediumPriorityCount:6,
        lowPriorityCount: 2,
        highEffortCount: 8,
        mediumEffortCount: 12,
        lowEffortCount: 1,
        highImpactCount: 10,
        mediumImpactCount: 15,
        lowImpactCount: 20,
    },
    recommendations: [
        {
            id: "rec-001",
            title: "Enhance App Onboarding Flow",
            issue_icon: "🚀",
            type: "product",
            priority: "high",
            estimated_effort: "medium",
            estimated_effort_days: 10,
            expected_outcome: "Reduce new user churn by 10%; Increase first-week engagement by 15%.",
            ai_rationale: "Analysis of reviews linked to 'Seamless User Experience' (ID: 1) and 'Attractive & Clean Design' (ID: 4) highlights a strong foundation. Optimizing the initial onboarding journey further can capitalize on these strengths, as new users often form first impressions critical to long-term retention.",
            recommended_actions: [
                {
                    action_title: "Action 1",
                    action_description: "Action 1 description",
                    estimated_effort: "low",
                    estimated_effort_days: 10
                },
            ],
            linked_analysis_ids: ["1", "4"], // Linked to multiple positive areas
            representative_review_id: "1" // ID only
        },
        {
            id: "rec-002",
            title: "Optimize Large File Transfer Performance",
            issue_icon: "🚀",
            type: "product",
            priority: "high",
            estimated_effort: "high",
            estimated_effort_days: 10,
            expected_outcome: "Reduce negative sentiment related to 'slow transfers' by 20%; Improve conversion rates for high-value transactions.",
            ai_rationale: "While 'Lightning-Fast Transactions' (ID: 1) generally receives high praise, a deeper dive into reviews related to this opportunity reveals sporadic mentions of delays with very large file transfers. Proactive optimization can maintain high satisfaction and 'Reliable Fund Transfers' (ID: 2) for all transaction sizes.",
            recommended_actions: [
                {
                    action_title: "Action 1",
                    action_description: "Action 1 description",
                    estimated_effort: "low",
                    estimated_effort_days: 10
                },
                {
                    action_title: "Action 2",
                    action_description: "Action 2 description",
                    estimated_effort: "low",
                    estimated_effort_days: 10
                },
                {
                    action_title: "Action 3",
                    action_description: "Action 3 description",
                    estimated_effort: "low",
                    estimated_effort_days: 10
                },
            ],
            linked_analysis_ids: ["1", "2"], // Linked to multiple positive areas
            representative_review_id: "2" 
        },
        {
            id: "rec-003",
            title: "Introduce Biometric Login Options",
            issue_icon: "🚀",
            type: "product",
            priority: "medium",
            estimated_effort: "medium",
            estimated_effort_days: 10,
            expected_outcome: "Increase daily active users by 5%; Boost app security perception.",
            ai_rationale: "Leverages the positive sentiment around 'Intuitive & User-Friendly Interface' (ID: 2) and contributes to 'Reliable Fund Transfers' (ID: 2) by offering secure, fast access. Biometric login aligns with user expectations for ease of access and modern security features, enhancing the overall 'Seamless User Experience' (ID: 1).",
            recommended_actions: [
                {
                    action_title: "Action 1",
                    action_description: "Action 1 description",
                    estimated_effort: "low",
                    estimated_effort_days: 10
                },
            ],
            linked_analysis_ids: ["1", "2"], // Linked to multiple positive areas
            representative_review_id: "3" 
        },
        {
            id: "rec-004",
            title: "Expand In-App Self-Service Options",
            issue_icon: "🚀",
            type: "product",
            priority: "medium",
            estimated_effort: "low",
            estimated_effort_days: 10,
            expected_outcome: "Reduce customer support inquiries by 15%; Increase user autonomy.",
            ai_rationale: "Builds on the success of 'Excellent Customer Support' (ID: 3) by empowering users to find answers quickly. Many common support queries (related to 'Seamless User Experience' ID: 1) could be resolved via an expanded FAQ or guided troubleshooting, enhancing overall user satisfaction.",
            recommended_actions: [
                {
                    action_title: "Action 1",
                    action_description: "Action 1 description",
                    estimated_effort: "low",
                    estimated_effort_days: 10
                },
            ],
            
            linked_analysis_ids: ["1", "3"], // Linked to multiple positive areas
            representative_review_id: "4" 
        },
        {
            id: "rec-005",
            title: "Gamify Savings Goals",
            issue_icon: "🚀",
            type: "product",
            priority: "low",
            estimated_effort: "high",
            estimated_effort_days: 10,
            expected_outcome: "Increase user stickiness and repeat app visits by 10%; Boost savings product uptake.",
            ai_rationale: "Derived from subtle positive feedback about 'Attractive & Clean Design' (ID: 4) combined with observed user behavior patterns around financial planning. This is an opportunity for innovation in user engagement, enhancing the overall 'Seamless User Experience' (ID: 1).",
            recommended_actions: [
                {
                    action_title: "Action 1",
                    action_description: "Action 1 description",
                    estimated_effort: "low",
                    estimated_effort_days: 10
                },
            ],
            linked_analysis_ids: ["1", "4"],
            representative_review_id: "1" 
        },
        {
            id: "rec-006",
            title: "Personalized Financial Tips",
            issue_icon: "🚀",
            type: "product",
            priority: "low",
            estimated_effort: "medium",
            estimated_effort_days: 10,
            recommended_actions: ["Create a new feature that allows users to set financial goals and track their progress.", "Create a new feature that allows users to set financial goals and track their progress.", "Create a new feature that allows users to set financial goals and track their progress."],
            expected_outcome: "Improve user financial literacy perception by 8%; Increase cross-product engagement.",
            ai_rationale: "An exploratory opportunity identified by correlating positive 'Easy to Use' sentiment (linked to 'Seamless User Experience' ID: 1) with emerging trends in personalized financial wellness. Offers a value-add that leverages existing user comfort with the app and aligns with the professional perception of 'Reliable Fund Transfers' (ID: 2).",
            linked_analysis_ids: ["1", "2"],
            representative_review_id: "3",
            recommended_actions: [
                {
                    action_title: "Action 1",
                    action_description: "Create a new feature that allows users to set financial goals and track their progress.",
                    estimated_effort: "low",
                    estimated_effort_days: 10
                },
            ],
        }
    ]
};